export const colors = {
  backgroundLightColor: '#F0F4EF',
  backgroundDarkColor: '#172533',
  textLinkColor: '#2ECBFF',
  lightBlueColor1: '#B8DBD9',
  lightBlueColor2: '#70A9A1',
  modalErrorColor: '#FF284C',
  modalSuccesColor: '#06D6A0',
  modalLoadingColor: '#3D5269',
  switchFocusedColor: '#86F872',
  grayColor: '#D9D9D9',
  menuOnFocusedLightColor: '#B4CDED',
  textMenuOnfocusedColor: '#2ECBFF',
  menuLightColor: '#B0B9C4',
  menuOnFocusedDarkColor: '#6F8AAD',
  menuDarkColor: '#FFFFFF',
  habitsItemLightColor1: '#B4CDED',
  habitsItemDarkColor1: '#6F8AAD',
  habitsItemDarkColor2: '#6E9492',
  lightGreenColor: '#A8D0B9',
};
